### ISSUE TITLE
Implémentation des fonctions de FRANCE BOT V3

### ISSUE THREAD

**Issue by LotharieSlayer** [uAtomicBoolean/FranceBotJS#12]
Faire les modules suivants :
- [x] Likes 
- [x] Moyenne
- [x] Repost
- [x] Feed
- [x] Stats
- [x] Logs
- [x] Threads
- [x] Reddit (module 'reddit')
- [x] Twitter (module 'twitter-api-v2')

**Comment by LotharieSlayer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FRANCE BOT V4 / JS](https://trello.com/c/2qqliPAN/40-france-bot-v4-js)

**Comment by uAtomicBoolean** [comment]
Les fonctionnalités Stats (anciennement StatsMensuelles) et Classement des emojis ont été mises ensemble.
Le classement des emojis est maintenant considéré comme une stat et les deux sont donc réunies dans le module 'Stats'.
Mais le fonctionnement reste le meme comme avant (une table pour les stats du serveur, une table pour le classement des emojis du mois, et une table pour l'historique des classements des emojis).
